app/posts/blueprint.py
from flask import Blueprint
from flask.templating import render_template

from models import Post, Tag

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def index():
    posts = Post.query.all()
    return render_template('posts/index.html', posts=posts)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Post.slug==slug).first()
    # posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag)

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint index
{% endblock %}

{% block content_title %}
    Posts
{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="container">
            <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
                <h2>{{post.title}}</h2>
            </a>
          
            <hr>
        </div>
    {% endfor %}
{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}


{% block content_title %}
{{post.title}}
{% endblock  %}

{% block content %}
<div class="container">
    <p>{{post.body}}</p>
    <span class="badge">{{ post.created }}</span>
    <div class="pull-right">
        <b>Tags:</b> 
        {% for tag in tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug)}}"><span class="label label-success">{{ tag.name }}</span></a>
        
        {% endfor %}
    </div>
</div>

{% endblock  %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
{{ tag.name }} posts
{% endblock %}

{% block content_title %}
   Post for {{tag.name}}
{% endblock %}

{% block content %}
  {%for post in posts %}
    <div class="post">
        <a href="{{ url_for('poasts.post_detail', slug=post.slug) }}">{{ posts.title }}</a>
    </div>
  {% endfor %}
{% endblock %}