app/models.py
from app import db 
from datetime import datetime
import re


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

post_tags = db.Table('post_tags',
                     db.Column('post_id',  db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )



class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(120))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()
    
    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    def __repr__(self):
        return '<Post id: {}, title: {}, slug: {} >'.format(self.id, self.title, self.slug)        

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name) 

    def __repr__(self):
        return '<Tag id: {}, name: {}, slug: {} >'.format(self.id, self.name, self.slug)

app/app.py
from flask import Flask
from config import Configuration

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)
migrate = Migrate(app, db)
migrate.init_app(app, db)

app/main.py
from app import app, db
from posts.blueprint import posts


import view

app.register_blueprint(posts, url_prefix="/blog")


if __name__ == '__main__':
   app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask.templating import render_template

from models import Post, Tag

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def index():
    posts = Post.query.all()
    return render_template('posts/index.html', posts=posts)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)

@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Post.slug==slug).first()
    # posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon"
        href="https://static.wixstatic.com/media/cd8cb6_3b0b8eb75c4c48fa932edc0dcfb64746~mv2.png/v1/fill/w_106,h_106,al_c,usm_0.66_1.00_0.01/blog%20haiyue.png"
        type="image/png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous">
    </script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <title>
        {% block title %} {% endblock %} | Flask app
    </title>
    <style>
        a:link, a:visited {
          
          color: #000;
         
          text-align: center;
          text-decoration: none;
          display: inline-block;
         
        }
        
        a:hover, a:active {
            color: rgb(63, 172, 117);
        }
        </style>
</head>

<body>
    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{{ url_for('index') }}" class="nav-link px-2 text-secondary">Home</a></li>
                    <li><a href="{{ url_for('posts.index')}}" class="nav-link px-2 text-white">Blog</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Linck</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">Linck</a></li>
                    <li><a href="#" class="nav-link px-2 text-white">About</a></li>
                </ul>

                <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                    <input type="search" class="form-control form-control-dark" placeholder="Search..."
                        aria-label="Search">
                </form>

                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2">Login</button>
                    <button type="button" class="btn btn-warning">Sign-up</button>
                </div>
            </div>
        </div>
    </header>

    <div class="container">

        <div class="col-md-12">
            <h1> {% block content_title %} {% endblock %}</h1>
            <p> <b>{% block content %} {% endblock %}</b> </p>
           

        </div>
    </div>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Home

{% endblock %}

{% block content_title %}
index page
{% endblock %}

{% block content %}
some content
{% endblock %}